// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {storage} from '../models';
import {scanner} from '../models';

export function AskAI(arg1:string):Promise<string>;

export function ClearAllData():Promise<void>;

export function ExportAndClear():Promise<string>;

export function ExportData(arg1:number):Promise<string>;

export function ExportDiagnosesData(arg1:number):Promise<string>;

export function ExportFullReport():Promise<string>;

export function GetAlertRules():Promise<main.AlertRules>;

export function GetAvailableModels():Promise<Array<string>>;

export function GetBaselines():Promise<Array<storage.Baseline>>;

export function GetCurrentModel():Promise<string>;

export function GetCurrentNetwork():Promise<Record<string, string>>;

export function GetCurrentStatus():Promise<main.StatusResponse>;

export function GetDNSResolverComparison(arg1:number):Promise<Array<storage.TimeseriesPoint>>;

export function GetDiagnosisHistory(arg1:number):Promise<Array<main.DiagnosisResponse>>;

export function GetDiagnosisTimeline(arg1:number):Promise<Array<storage.DiagnosisPeriod>>;

export function GetGatewayVsExternal(arg1:number):Promise<Array<storage.ProbeLatencyPoint>>;

export function GetHeatmap(arg1:number):Promise<Array<storage.HeatmapCell>>;

export function GetJitterHistory(arg1:number):Promise<Array<storage.TimeseriesPoint>>;

export function GetNetworkDevices():Promise<Array<scanner.Device>>;

export function GetNetworkEvents(arg1:number):Promise<Array<storage.NetworkEvent>>;

export function GetPacketLossHistory(arg1:number):Promise<Array<storage.TimeseriesPoint>>;

export function GetProjectReport():Promise<main.ProjectReportData>;

export function GetRecentProbes(arg1:number):Promise<Array<main.ProbeResultResponse>>;

export function GetSpeedTestResults(arg1:number):Promise<Array<main.SpeedTestResponse>>;

export function GetUptimeStats():Promise<main.UptimeStats>;

export function GetWifiInfo():Promise<main.WifiInfo>;

export function GetWifiSignalHistory(arg1:number):Promise<Array<storage.WifiTimeseriesPoint>>;

export function RunSpeedTest():Promise<main.SpeedTestResponse>;

export function ScanNetwork():Promise<Array<scanner.Device>>;

export function SetAlertRules(arg1:main.AlertRules):Promise<void>;

export function SetModel(arg1:string):Promise<void>;
