// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskAI(arg1) {
  return window['go']['main']['App']['AskAI'](arg1);
}

export function ClearAllData() {
  return window['go']['main']['App']['ClearAllData']();
}

export function ExportAndClear() {
  return window['go']['main']['App']['ExportAndClear']();
}

export function ExportData(arg1) {
  return window['go']['main']['App']['ExportData'](arg1);
}

export function ExportDiagnosesData(arg1) {
  return window['go']['main']['App']['ExportDiagnosesData'](arg1);
}

export function ExportFullReport() {
  return window['go']['main']['App']['ExportFullReport']();
}

export function GetAlertRules() {
  return window['go']['main']['App']['GetAlertRules']();
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetBaselines() {
  return window['go']['main']['App']['GetBaselines']();
}

export function GetCurrentModel() {
  return window['go']['main']['App']['GetCurrentModel']();
}

export function GetCurrentNetwork() {
  return window['go']['main']['App']['GetCurrentNetwork']();
}

export function GetCurrentStatus() {
  return window['go']['main']['App']['GetCurrentStatus']();
}

export function GetDNSResolverComparison(arg1) {
  return window['go']['main']['App']['GetDNSResolverComparison'](arg1);
}

export function GetDiagnosisHistory(arg1) {
  return window['go']['main']['App']['GetDiagnosisHistory'](arg1);
}

export function GetDiagnosisTimeline(arg1) {
  return window['go']['main']['App']['GetDiagnosisTimeline'](arg1);
}

export function GetGatewayVsExternal(arg1) {
  return window['go']['main']['App']['GetGatewayVsExternal'](arg1);
}

export function GetHeatmap(arg1) {
  return window['go']['main']['App']['GetHeatmap'](arg1);
}

export function GetJitterHistory(arg1) {
  return window['go']['main']['App']['GetJitterHistory'](arg1);
}

export function GetNetworkEvents(arg1) {
  return window['go']['main']['App']['GetNetworkEvents'](arg1);
}

export function GetPacketLossHistory(arg1) {
  return window['go']['main']['App']['GetPacketLossHistory'](arg1);
}

export function GetProjectReport() {
  return window['go']['main']['App']['GetProjectReport']();
}

export function GetRecentProbes(arg1) {
  return window['go']['main']['App']['GetRecentProbes'](arg1);
}

export function GetSpeedTestResults(arg1) {
  return window['go']['main']['App']['GetSpeedTestResults'](arg1);
}

export function GetUptimeStats() {
  return window['go']['main']['App']['GetUptimeStats']();
}

export function GetWifiInfo() {
  return window['go']['main']['App']['GetWifiInfo']();
}

export function GetWifiSignalHistory(arg1) {
  return window['go']['main']['App']['GetWifiSignalHistory'](arg1);
}

export function RunSpeedTest() {
  return window['go']['main']['App']['RunSpeedTest']();
}

export function SetAlertRules(arg1) {
  return window['go']['main']['App']['SetAlertRules'](arg1);
}

export function SetModel(arg1) {
  return window['go']['main']['App']['SetModel'](arg1);
}
